events {}

http {
    upstream control_plane {
        server control-plane:80;
    }

    log_format csv '$msec,$status';

    server {
        listen 80;
        access_log /metrics/nginx_access.log csv;

        location / {
            proxy_pass http://control_plane;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
