events {}

http {
    upstream control_plane {
        server control-plane:80;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://control_plane;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
