#!/usr/bin/env python3
"""
Plotting script for Marc Brooker's blog reproduction.
Reads summary.csv generated by run_sweep.py
"""

import argparse
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

def plot_brooker_repro(results_dir: str, output_dir: str):
    results_path = Path(results_dir)
    print(results_path)
    summary_path = results_path / "summary.csv"
    
    if not summary_path.exists():
        # Fallback: look for inner sweep dir if results_dir is the top level
        # Workflow passes {scenario}_sweep_{ts} as output_dir. behavior of run_sweep is to use output_dir/{config}_sweep_{ts}
        # Wait, run_sweep creates `output_dir / f"{yaml_path.stem}_sweep_{timestamp}"`
        # workflow passes `output_base` (e.g. results/brooker_repro_{ts}) to run_sweep.
        # So run_sweep creates `results/brooker_repro_.../brooker_repro_sweep_.../summary.csv`.
        # This nesting is slightly annoying.
        # Let's search recursively for summary.csv
        found = list(results_path.rglob("summary.csv"))
        if not found:
            print(f"Error: Could not find summary.csv in {results_dir}")
            return
        summary_path = found[0]
        print(f"Found summary data at: {summary_path}")

    df = pd.read_csv(summary_path)
    
    # Ensure output dir exists
    out_path = Path(output_dir)
    out_path.mkdir(parents=True, exist_ok=True)
    
    # 1. Success Rate vs Failure Rate
    plt.figure(figsize=(10, 6))
    # We use the first service's p_fail as the x-axis, assuming lockstep sweep
    x_axis = "services.0.partial_failures.0.p_fail"
    if x_axis not in df.columns:
        print(f"Warning: Column {x_axis} not found. Plotting might fail. Available keys: {df.columns}")
        
    sns.lineplot(data=df, x=x_axis, y="success_rate", hue="client_name", marker="o")
    plt.title("Client Success Rate vs Server Failure Rate")
    plt.xlabel("Server Failure Rate")
    plt.ylabel("Client Success Rate")
    plt.grid(True, alpha=0.3)
    plt.ylim(0, 1.05)
    plt.savefig(out_path / "success_rate_vs_failure.png")
    plt.close()
    
    # 2. Goodput vs Failure Rate
    plt.figure(figsize=(10, 6))
    sns.lineplot(data=df, x=x_axis, y="goodput_rps", hue="client_name", marker="o")
    plt.title("Client Goodput vs Server Failure Rate")
    plt.xlabel("Server Failure Rate")
    plt.ylabel("Goodput (RPS)")
    plt.grid(True, alpha=0.3)
    plt.savefig(out_path / "goodput_vs_failure.png")
    plt.close()
    
    # 3. Load (Total Requests) vs Failure Rate
    # This shows "Efficiency" or "Retry Storm" effect
    plt.figure(figsize=(10, 6))
    sns.lineplot(data=df, x=x_axis, y="total_requests", hue="client_name", marker="o")
    plt.title("Total Load vs Server Failure Rate")
    plt.xlabel("Server Failure Rate")
    plt.ylabel("Total Requests Sent (original + retries)")
    plt.grid(True, alpha=0.3)
    plt.savefig(out_path / "load_vs_failure.png")
    plt.close()

    print(f"Plots generated in {out_path}")

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("results_dir", help="Directory containing simulation results")
    parser.add_argument("-o", "--output", help="Output directory for plots")
    args = parser.parse_args()
    
    plot_brooker_repro(args.results_dir, args.output or args.results_dir)

if __name__ == "__main__":
    main()
